### ISSUE TITLE
spawn_mobs not working

### ISSUE THREAD

**Issue by Sedri05** [Auxilor/libreforge#11]
**Describe the bug**
spawn_mobs does not spawn any mobs. There are also no errors.

**To Reproduce**
Make an item with a spawn_mobs effect

**Expected behavior**
The mob you want is supposed to spawn.

**Server Information (please complete the following information):**
- Version: git-Paper-388 (MC: 1.17.1)
- Version of plugin and eco:
   eco version 6.20.4
   EcoItems version 3.17.3

**Additional context**
The effect:
```   effects:
      - id: spawn_mobs
        args:
          amount: 5
          ticks_to_live: 1200
          health: 20
          range: 1
          entity: wolf	
        triggers:
          - alt_click
```
I tried both wolf and zombie and both times it didnt spawn anything

**Comment by WillFP** [comment]
Fixed in 3.7.6
