### ISSUE TITLE
cancel_event effect bug

### ISSUE THREAD

**Issue by LuluxClient** [Auxilor/libreforge#15]
**Describe the bug**
When using the cancel_event with the mine_block or the mine_block_progress it is not stopping me from breaking a block and I cannot add a filter with ecoenchants
**To Reproduce**
1. go to customenchants.yml
2. copypaste this: https://pastebin.com/J40Ktk41
3. do /ecoenchants reload
4. grab a pickaxe and do /enchants toucher_de_druse 1
5. mine a budding amethyst block or any block

**Expected behavior**
it should prevent me from breaking the block

**Screenshots**
none

**Server Information (please complete the following information):**
- Version: (output of `/ver` command)
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)

eco version 6.24.1

**Additional context**
It would be cool to add everything with the cancel event so we could cancel stuff such as EAT so prevent players to eat something or USE to prevent players to use totems or swords etc

**Comment by WillFP** [comment]
Should be fixed in next version
