### ISSUE TITLE
make damage_nearby_entities not need a entities argument

### ISSUE THREAD

**Issue by Sedri05** [Auxilor/libreforge#19]
**Is your feature request related to a problem? Please describe.**
Yes I'm trying to make a item that damages all entities in a certain radius but I don't want to manually type in all Minecraft entities

**Describe the solution you'd like**
When creating a effect you should be able to leave out the entities argument and then it just damages all entities

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by WillFP** [comment]
Coming in next version
