### ISSUE TITLE
cancel_event effect bug #2

### ISSUE THREAD

**Issue by LuluxClient** [Auxilor/libreforge#29]
**Describe the bug**
When using the cancel_event with the mine_block or the mine_block_progress it is not stopping me from breaking a block and I cannot add a filter with ecoenchants
**To Reproduce**
1. go to customenchants.yml
2. copypaste this: https://pastebin.com/J40Ktk41
3. do /ecoenchants reload
4. grab a pickaxe and do /enchants toucher_de_druse 1
5. mine a budding amethyst block or any block

**Expected behavior**
it should prevent me from breaking the block

**Screenshots**
none

**Server Information (please complete the following information):**
- Version: (output of `/ver` command)
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
- 1.18.2

eco version 6.35.6

**Additional context**
I already reported this issue but it did not get fixed. https://github.com/Auxilor/libreforge/issues/15

**Comment by WillFP** [comment]
Latest ecoenchants, latest eco - just tried it (copied over your configuration), and it works perfectly

**Comment by LuluxClient** [comment]
> 

Hey could you provide your configs or a gif, here is what I'm doing (maybe I'm dumb): 

https://gyazo.com/926bfd189bd69bbf5adfb391466b9318

**Comment by WillFP** [comment]
Yep i copied your config exactly and it worked for me - it's entirely possible that since you're OP one of your plugins is overriding the cancellation

**Comment by LuluxClient** [comment]
> Yep i copied your config exactly and it worked for me - it's entirely possible that since you're OP one of your plugins is overriding the cancellation

Hello I tested with only these plugins: 
[19:51:11 INFO]: Plugins (14): BungeeGuard, eco, EcoArmor, EcoCrates, EcoDurability, EcoEnchants, EcoEnchantsGUI, EcoItems, EcoSkills, JPremium, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, Vault

With this it still doesn't work, could you provide me some info with ur setup ?
https://gyazo.com/7fa1ddcd5f021da547baeda208a309bc

**Comment by LuluxClient** [comment]
Tried with only this : 
![image](https://user-images.githubusercontent.com/62576432/169708856-037521a2-179f-493d-bf8a-4f5f56bb02bd.png)
still not working
