### ISSUE TITLE
arrow_ring effect ignores pvp protections when triggered by a player

### ISSUE THREAD

**Issue by KermX** [Auxilor/libreforge#33]
**Describe the bug**
arrow_ring effect ignores pvp restrictions 

**To Reproduce**
1. use arrow_ring effect on something that can be triggered by a player (ex a custom enchant)
2. use on another player in a pvp protected area

**Expected behavior**
arrow_ring effect should respect pvp protections when triggered by a player.

**Server Information (please complete the following information):**
- Version: git-Paper-379
- Eco version:  6.36.4

**Comment by WillFP** [comment]
When does this happen? e.g. when a player shoots an arrow at a PvP protected player, or is it when they shoot an arrow _near_ a PvP protected player?
I'm assuming arrow_ring is a bow enchant for the sake of this

**Comment by KermX** [comment]
I have it set up as a bow enchant that is triggered with the swing trigger. So given your example I'd assume it's equivalent to shooting an arrow near a player
