### ISSUE TITLE
item component in trigger data and item filter

### ISSUE THREAD

**Issue by the-Astra** [Auxilor/libreforge#37]
**Is your feature request related to a problem? Please describe.**
Currently, Eco has no way of checking held items or requiring items for triggers. Having this as an option would open so many opportunities for creativity.

**Describe the solution you'd like**
Simply put, some way to track a currently held item (or lack if a held item)

**Describe alternatives you've considered**
N/A. This is a unique feature request.

**Additional context**
N/A

**Comment by WillFP** [comment]
Coming in next update, already implemented it!
