### ISSUE TITLE
Add a configurable gain_[effect] trigger

### ISSUE THREAD

**Issue by the-Astra** [Auxilor/libreforge#38]
**Is your feature request related to a problem? Please describe.**
After trying to create a pet, I found that I need the player to gain a specific effect for the pet to level up, and the has_potion_effect condition does not trigger this.

**Describe the solution you'd like**
Simply put, a trigger that checks when a player receives a certain effect.

**Describe alternatives you've considered**
The has_potion_effect condition, as explained above.

**Additional context**
This is for the Ravager pet, which Auxilor was going to add to EcoPets, but likely could not due to this.

**Comment by WillFP** [comment]
Added win_raid trigger instead
