### ISSUE TITLE
Evoker Bone Attack for Custom Entity AI

### ISSUE THREAD

**Issue by the-Astra** [Auxilor/libreforge#46]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The implementation of an Entity Goal that executes the Evoker bone attack aimed at the target.

**Describe alternatives you've considered**
N/A, I do not believe any alternatives exist for this.

**Additional context**
N/A

**Comment by WillFP** [comment]
Can you move this to eco?
