### ISSUE TITLE
Shoot effect does not work

### ISSUE THREAD

**Issue by KermX** [Auxilor/libreforge#48]
**Describe the bug**
The shoot effect does not work, all projectiles are unsupported

**To Reproduce**
1. Create an item or custom enchant that uses the shoot effect (I believe the trigger and all other variables can be anything)
2. Try to use said item or enchant.

**Expected behavior**
A projectile should be shot.

**Screenshots**

**Server Information (please complete the following information):**
- Version: git-PufferfishPlus-21 (MC: 1.19.2)
- Version eco: eco version 6.38.3
- Version ecoitems: EcoItems version 3.99.0
- Version ecoenchants: EcoEnchants version 8.110.0

**Additional context**
(https://pastebin.com/Xsg6sj2M) Pastebin of error when attempting.

**Comment by WillFP** [comment]
You can only shoot projectile entities (send me your config if i'm wrong here)
