### ISSUE TITLE
Add more support to aureliumskills 

### ISSUE THREAD

**Issue by TadaClip** [Auxilor/libreforge#60]
**Is your feature request related to a problem? Please describe.**
On the wiki it says that skill_xp_multiplier works for ecoskills and aureliumskills but there is no support for aureliumskills in this effect.

**Describe the solution you'd like**
add skill_xp_multiplier to aureliumskills

**Describe alternatives you've considered**
Could you add the same effects and triggers that ecoskills has to aureliumskills?

I know you probably don't make it so that ecoskills stand out in your ecosystem, but why not add more support for existing 3rd party plugins?

![Captura de Pantalla 2022-10-04 a la(s) 21 30 18](https://user-images.githubusercontent.com/114841751/193966654-8619b89e-5dc4-48ae-b658-946f51b7694e.png)

**Comment by WillFP** [comment]
Fix coming in next update
