### ISSUE TITLE
triggers dont working in worldguard protected regions

### ISSUE THREAD

**Issue by TadaClip** [Auxilor/libreforge#64]
**Describe the bug**
The triggers alt_click, mine_block and place_block dont work in protected regions (like spawns) where worldguard cancels these events with the flags block-break: deny and block-place: deny

**To Reproduce**
1. Place a region with the flags block-break: deny and block-place: deny
2. Place a trigger alt_click, mine_block or place_block anywhere
3. Take off the operator mode (deop)
4. Try to call the trigger
5. The trigger is not activated

**Expected behavior**
Activate the trigger anywhere

**Server Information (please complete the following information):**
- Version: git-Paper-210 (MC: 1.19.2)
- Version of plugin and eco: eco version 6.43.7, EcoItems version 3.126.0

**Comment by WillFP** [comment]
Add disable_antigrief_check: true, it's in the wiki
